# Generated by Django 5.1.7 on 2025-07-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_association_last_farmer_number_and_more'),
        ('users', '0002_association_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='association.association'),
        ),
        migrations.DeleteModel(
            name='Association',
        ),
    ]
