# Generated by Django 5.1.7 on 2025-06-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_association_customuser_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='association',
        ),
        migrations.DeleteModel(
            name='Association',
        ),
    ]
