# Generated by Django 5.1.7 on 2025-04-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_userprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
