# Generated by Django 5.1.7 on 2025-04-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_userprofile_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='member',
            new_name='user',
        ),
    ]
