# Generated by Django 5.1.7 on 2025-04-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
