# Generated by Django 5.1.7 on 2025-07-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='age',
        ),
    ]
