# Generated by Django 5.1.7 on 2025-07-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_remove_farmer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='last_farmer_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='association',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
