# Generated by Django 5.1.7 on 2025-06-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='receipts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
