# Generated by Django 5.1.7 on 2025-06-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_financials_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
