# Generated by Django 5.1.7 on 2025-04-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_federation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Federation',
        ),
    ]
