# Generated by Django 5.1.7 on 2025-04-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_delete_federation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financials',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
