# Generated by Django 5.1.7 on 2025-07-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_initial'),
        ('financial', '0004_alter_financials_admin'),
    ]

    operations = [
    ]
