# Generated by Django 5.1.7 on 2025-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitems',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
