# Generated by Django 5.1.7 on 2025-04-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitems_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryrental',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
