# Generated by Django 5.1.7 on 2025-04-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_admin_id_inventoryrental_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitems',
            name='unit',
        ),
    ]
