from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView
from users.views import CustomTokenObtainPairView
from . import views

urlpatterns = [
     path("members/",
         views.members,
         name="members"),
     path("pending_members",
          views.pending_members,
          name="pending_members"),
     path("rejected_members",
          views.rejected_members,
          name="rejected_members"),
     path("add_members/",
         views.add_members,
         name="add_member"),
     path("delete_members/<uuid:user_id>",
         views.delete_members,
         name="delete_member"),
     path("update_member/<uuid:user_id>",
         views.update_member,
         name="update_member"),
     path("member_profile/<uuid:user_id>",
         views.member_profile,
         name="member_profile"),
     path("create_member_profile/<uuid:user_id>",
         views.create_member_profile,
         name="add_member"),
     path("update_member_profile/<uuid:user_id>",
         views.update_member_profile,
         name="update_member"),
     path('user_with_profile/<uuid:user_id>/', 
          views.get_user_with_profile, 
          name="user_with_profile"),
     path("request-verification/", 
          views.request_email_verification,
          name="request-verification"),
     path("verify-email/", 
          views.verify_email,
          name="verify-email"),
     path("signup/",
          views.signup,
          name="signup"),
     path('api/token/',
          CustomTokenObtainPairView.as_view(), 
          name='token_obtain_pair'),
     path('api/token/refresh/', 
          TokenRefreshView.as_view(), 
          name='token_refresh'),
     path('api/protected/', 
          views.ProtectedView.as_view(), 
          name='protected_view'),
     path('api/logout/', 
          views.logout_view, 
          name='logout'),
     path('accept_member/<uuid:user_id>/', 
          views.accept_member, 
          name="accept_member"),
     path('reject_member/<uuid:user_id>/', 
          views.reject_member, 
          name="reject_member"),
]
