# Generated by Django 5.1.7 on 2025-06-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_dailyordercounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyOrderCounter',
        ),
    ]
