# Generated by Django 5.1.7 on 2025-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('out_of_stock', 'Out of Stock'), ('hidden', 'Hidden'), ('pending_approval', 'Pending Approval'), ('deleted', 'Deleted'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
    ]
