# Generated by Django 5.1.7 on 2025-06-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_farmer_code_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('out_of_stock', 'Out of Stock'), ('hidden', 'Hidden'), ('pending_approval', 'Pending Approval'), ('deleted', 'Deleted'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
    ]
