# Generated by Django 5.1.7 on 2025-06-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariation_unit_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='unit_measurement',
            field=models.CharField(max_length=100),
        ),
    ]
